// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWsWXAYXZx6IXI5axkk8wf1E1ck9O_FbM',
    appId: '1:550997604028:android:192f2670958d919559c2b9',
    messagingSenderId: '550997604028',
    projectId: 'aarohan-76222',
    databaseURL: 'https://aarohan-76222.firebaseio.com',
    storageBucket: 'aarohan-76222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeB2kUD8VetP1PiWHhZ8ggNMXPyKsbzd4',
    appId: '1:550997604028:ios:b31e93364bf3957e59c2b9',
    messagingSenderId: '550997604028',
    projectId: 'aarohan-76222',
    databaseURL: 'https://aarohan-76222.firebaseio.com',
    storageBucket: 'aarohan-76222.appspot.com',
    androidClientId:
        '550997604028-297d0dbi2sd81hrpfo3tl6bsld58es24.apps.googleusercontent.com',
    iosClientId:
        '550997604028-682susoa035683vr4d3h14m49s4fc8fo.apps.googleusercontent.com',
    iosBundleId: 'com.app.aarohan.aarohanapp',
  );
}
